# SPDX-License-Identifier: Apache-2.0
---
- name: Install EPEL repo (rpm)
  ansible.builtin.dnf:
    name: epel-release
    state: present
  when: 'ansible_distribution == "CentOS"'

- name: Install systemd-timesyncd
  ansible.builtin.package:
    name:
      - systemd-timesyncd
    state: present

- name: Enable systemd-timesyncd
  ansible.builtin.systemd:
    enabled: true
    name: systemd-timesyncd
    state: started
  notify: Wait 5s for NTP sync
