# SPDX-License-Identifier: Apache-2.0
---
- name: Set facts from variables for cross host queries
  ansible.builtin.set_fact:
    cacheable: true
    ovn_name: "{{ ovn_name }}"
    ovn_az_name: "{{ ovn_az_name }}"
    ovn_roles: "{{ ovn_roles }}"

- name: Set ovn_ip_address fact from variable if exists
  ansible.builtin.set_fact:
    cacheable: true
    ovn_ip_address: "{{ ovn_ip_address }}"
  when: "ovn_ip_address is defined"

- name: Add keys and certificates generation tasks
  ansible.builtin.import_tasks: certificates.yml
  when: ansible_distribution in ("Ubuntu", "Debian")

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  when: ansible_distribution in ("Ubuntu", "Debian")

- name: Register the Debian repository
  ansible.builtin.import_tasks: "repo_deb.yml"
  when: ansible_distribution in ("Ubuntu", "Debian")

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  when: ansible_distribution in ("Ubuntu", "Debian")

- name: Install packages
  ansible.builtin.import_tasks: "packages.yml"
  when: ansible_distribution in ("Ubuntu", "Debian")

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
  when: ansible_distribution in ("Ubuntu", "Debian")

- name: Configure daemons
  ansible.builtin.import_tasks: "configuration.yml"
  when: ansible_distribution in ("Ubuntu", "Debian")
