# SPDX-License-Identifier: Apache-2.0
---
ovn_path: "../data/ovn/{{ ovn_name }}/"
ovn_central_southbound: >-
  {{ lookup('template', 'ovn-central.servers.j2') |
  from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\1]:6642') | join(',') }}
