# SPDX-License-Identifier: Apache-2.0
---
- name: Add the Debian repository registration
  ansible.builtin.import_tasks: repo_deb.yml

- name: Flush the handlers
  ansible.builtin.meta: flush_handlers

- name: Install the package for Linstor
  ansible.builtin.import_tasks: installation.yml

- name: Enable Linstor Services
  ansible.builtin.import_tasks: services.yml

- name: Create Linstor Satellite
  ansible.builtin.import_tasks: satellite.yml

- name: Create storage pool and add the disks
  ansible.builtin.import_tasks: storage.yml
