# SPDX-License-Identifier: Apache-2.0
---
- name: Add keys and dertificates generation handlers
  ansible.builtin.import_tasks: certificates.yml

- name: Add the repository registration handlers
  ansible.builtin.import_tasks: repo_deb.yml

- name: Add the package installation handlers
  ansible.builtin.import_tasks: packages.yml

- name: Add the daemons configuration handlers
  ansible.builtin.import_tasks: "configuration.yml"
