---
- name: Ceph - Deploy with the ceph role
  hosts: all
  collections:
    - lxc.incus
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "default_ipv4"
    - "default_ipv6"
    - "distribution_release"
  any_errors_fatal: true
  roles:
    - role: ceph

- name: Ceph - Deploy mon
  hosts: all
  order: shuffle
  gather_facts: no
  vars:
    task_fsid: "{{ ceph_fsid | default('') }}"
    task_roles: "{{ ceph_roles | default([]) }}"
  any_errors_fatal: true
  tasks:
    - name: Bootstrap Ceph mon
      shell:
        cmd: sudo -u ceph ceph-mon --mkfs -i {{ inventory_hostname_short }} --monmap /var/lib/ceph/bootstrap-mon/ceph.monmap --keyring /var/lib/ceph/bootstrap-mon/ceph.keyring
        creates: /var/lib/ceph/mon/ceph-{{ inventory_hostname_short }}/keyring
      notify:
        - Enable msgr2
        - Disable insecure_global_id_reclaim
      when: '"mon" in task_roles'

    - name: Enable and start Ceph mon
      systemd:
        enabled: yes
        name: ceph-mon@{{ inventory_hostname_short }}
        state: started
      when: '"mon" in task_roles'

  handlers:
    - name: Enable msgr2
      shell:
        cmd: ceph mon enable-msgr2

    - name: Disable insecure_global_id_reclaim
      shell:
        cmd: ceph config set global auth_allow_insecure_global_id_reclaim false

- name: Ceph - Deploy osd
  hosts: all
  order: shuffle
  gather_facts: no
  vars:
    task_disks: "{{ ceph_disks | default([]) }}"
    task_fsid: "{{ ceph_fsid | default('') }}"
    task_roles: "{{ ceph_roles | default([]) }}"
  any_errors_fatal: true
  tasks:
    - name: Bootstrap Ceph OSD
      shell:
        cmd: ceph-volume lvm create --data /dev/disk/by-id/{{ item.data }}{% if "db" in item %} --block.db /dev/disk/by-id/{{ item.db }}{% endif %}
        creates: /var/lib/ceph/osd/.{{ item.data }}.created
      loop: '{{ task_disks }}'
      when: '"osd" in task_roles'

    - name: Bootstrap Ceph OSD (stamp)
      shell:
        cmd: touch /var/lib/ceph/osd/.{{ item.data }}.created
        creates: /var/lib/ceph/osd/.{{ item.data }}.created
      loop: '{{ task_disks }}'
      when: '"osd" in task_roles'

- name: Ceph - Deploy mgr
  hosts: all
  order: shuffle
  gather_facts: no
  vars:
    task_fsid: "{{ ceph_fsid | default('') }}"
    task_roles: "{{ ceph_roles | default([]) }}"
  any_errors_fatal: true
  tasks:
    - name: Create /var/lib/ceph/mgr/ceph-{{ inventory_hostname_short }}
      file:
        path: /var/lib/ceph/mgr/ceph-{{ inventory_hostname_short }}
        owner: ceph
        group: ceph
        mode: 0770
        state: directory
      register: deploy_mgr
      when: '"mgr" in task_roles'

    - name: Create mgr keyring
      delegate_to: "{{ lookup('template', '../files/ceph/ceph.monitors.names.tpl') | from_yaml | first }}"
      shell:
        cmd: ceph auth get-or-create mgr.{{ inventory_hostname_short }} mon 'allow profile mgr' osd 'allow *' mds 'allow *'
      register: mgr_keyring
      when: '"mgr" in task_roles and deploy_mgr.changed'

    - name: Transfer mgr keyring
      copy:
        content: "{{ mgr_keyring.stdout }}\n"
        dest: "/var/lib/ceph/mgr/ceph-{{ inventory_hostname_short }}/keyring"
        owner: ceph
        group: ceph
        mode: 0660
      when: '"mgr" in task_roles and deploy_mgr.changed'

    - name: Enable ceph mgr
      systemd:
        enabled: yes
        name: ceph-mgr@{{ inventory_hostname_short }}
        state: started
      when: '"mgr" in task_roles'

- name: Ceph - Deploy mds
  hosts: all
  order: shuffle
  gather_facts: no
  vars:
    task_fsid: "{{ ceph_fsid | default('') }}"
    task_roles: "{{ ceph_roles | default([]) }}"
  any_errors_fatal: true
  tasks:
    - name: Create /var/lib/ceph/mds/ceph-{{ inventory_hostname_short }}
      file:
        path: /var/lib/ceph/mds/ceph-{{ inventory_hostname_short }}
        owner: ceph
        group: ceph
        mode: 0770
        state: directory
      register: deploy_mds
      when: '"mds" in task_roles'

    - name: Create mds keyring
      delegate_to: "{{ lookup('template', '../files/ceph/ceph.monitors.names.tpl') | from_yaml | first }}"
      shell:
        cmd: ceph auth get-or-create mds.{{ inventory_hostname_short }} mon 'profile mds' mgr 'profile mds' mds 'allow *' osd 'allow *'
      register: mds_keyring
      when: '"mds" in task_roles and deploy_mds.changed'

    - name: Transfer mds keyring
      copy:
        content: "{{ mds_keyring.stdout }}\n"
        dest: "/var/lib/ceph/mds/ceph-{{ inventory_hostname_short }}/keyring"
        owner: ceph
        group: ceph
        mode: 0660
      when: '"mds" in task_roles and deploy_mds.changed'

    - name: Enable ceph mds
      systemd:
        enabled: yes
        name: ceph-mds@{{ inventory_hostname_short }}
        state: started
      when: '"mds" in task_roles'

- name: Ceph - Deploy rgw
  hosts: all
  order: shuffle
  gather_facts: no
  vars:
    task_fsid: "{{ ceph_fsid | default('') }}"
    task_roles: "{{ ceph_roles | default([]) }}"
  any_errors_fatal: true
  tasks:
    - name: Create /var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname_short }}
      file:
        path: /var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname_short }}
        owner: ceph
        group: ceph
        mode: 0770
        state: directory
      register: deploy_rgw
      when: '"rgw" in task_roles'

    - name: Create Ceph rgw keyring
      delegate_to: "{{ lookup('template', '../files/ceph/ceph.monitors.names.tpl') | from_yaml | first }}"
      shell:
        cmd: ceph auth get-or-create client.rgw.{{ inventory_hostname_short }} mon 'allow rw' osd 'allow rwx'
      register: rgw_keyring
      when: '"rgw" in task_roles and deploy_rgw.changed'

    - name: Transfer rgw keyring
      copy:
        content: "{{ rgw_keyring.stdout }}\n"
        dest: "/var/lib/ceph/radosgw/ceph-rgw.{{ inventory_hostname_short }}/keyring"
        owner: ceph
        group: ceph
        mode: 0660
      when: '"rgw" in task_roles and deploy_rgw.changed'

    - name: Enable ceph rgw
      systemd:
        enabled: yes
        name: ceph-radosgw@rgw.{{ inventory_hostname_short }}
        state: started
      when: '"rgw" in task_roles'

- name: Ceph - Deploy rbd-mirror
  hosts: all
  order: shuffle
  gather_facts: no
  vars:
    task_fsid: "{{ ceph_fsid | default('') }}"
    task_roles: "{{ ceph_roles | default([]) }}"
  any_errors_fatal: true
  tasks:
    - name: Enable ceph rbd-mirror
      systemd:
        enabled: yes
        name: ceph-rbd-mirror@admin
        state: started
      when: '"rbd-mirror" in task_roles'
