---
- name: Environment checks
  hosts: all
  order: shuffle
  any_errors_fatal: true
  gather_facts: false
  tasks:
    - name: Verify NTP successfully synced
      shell:
        cmd: timedatectl timesync-status
      register: ntp_status_output
      failed_when: '"Packet count: 0" in ntp_status_output.stdout'
      changed_when: false
