---
- name: Incus - Add package repository (apt)
  hosts: all
  collections:
    - lxc.incus
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "default_ipv4"
    - "default_ipv6"
    - "distribution_release"
  any_errors_fatal: true
  roles:
    - role: incus
