- name: LVM Cluster - Generate configuration
  hosts: all
  collections:
    - lxc.incus
  order: shuffle
  gather_facts: true
  gather_subset:
    - "distribution_release"
  any_errors_fatal: true
  roles:
    - role: lvmcluster
