---
- name: Netplan - Override system configuration
  hosts: all
  collections:
    - lxc.incus
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
  any_errors_fatal: true
  roles:
    - role: netplan
