---
- name: NVME - Install packages and host config
  hosts: all
  collections:
    - lxc.incus
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
  roles:
    - role: nvme
