---
- name: OVN - Certificates and Packages
  collections:
    - lxc.incus
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "distribution_release"
  any_errors_fatal: true
  roles:
    - role: ovn

- name: OVN - Set up daemon configuration
  hosts: all
  order: shuffle
  gather_facts: yes
  gather_subset:
    - "default_ipv4"
    - "default_ipv6"
  vars:
    task_ip_address: "{{ ovn_ip_address | default(ansible_default_ipv6['address'] | default(ansible_default_ipv4['address'])) }}"
    task_az_name: "{{ ovn_az_name | default('') }}"
    task_name: "{{ ovn_name | default('') }}"
    task_roles: "{{ ovn_roles | default([]) }}"

    task_central_northbound: "{{ lookup('template', '../files/ovn/ovn-central.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6641') | join(',') }}"
    task_central_southbound: "{{ lookup('template', '../files/ovn/ovn-central.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6642') | join(',') }}"
    task_ic_northbound: "{{ lookup('template', '../files/ovn/ovn-ic.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6645') | join(',') }}"
    task_ic_southbound: "{{ lookup('template', '../files/ovn/ovn-ic.servers.tpl') | from_yaml | map('regex_replace', '^(.*)$', 'ssl:[\\1]:6646') | join(',') }}"
    task_pki_path: "../data/ovn/{{ task_name }}/"
  any_errors_fatal: true
  tasks:
    - name: Check if distribution is supported
      meta: end_play
      when: 'ansible_distribution not in ("Ubuntu", "Debian")'

    - name: Create OVN config directory
      file:
        path: /etc/ovn
        mode: 0755
        state: directory
      when: 'task_roles | length > 0'

    - name: Transfer OVN CA certificate
      copy:
        src: "{{ task_pki_path }}/ca.crt"
        dest: /etc/ovn/{{ task_name }}.ca.crt
        mode: 0644
      when: 'task_roles | length > 0'

    - name: Transfer OVN server certificate
      copy:
        src: "{{ task_pki_path }}/{{ inventory_hostname }}.crt"
        dest: /etc/ovn/{{ task_name }}.server.crt
        mode: 0644
      when: 'task_roles | length > 0'

    - name: Transfer OVN server key
      copy:
        src: "{{ task_pki_path }}/{{ inventory_hostname }}.key"
        dest: /etc/ovn/{{ task_name }}.server.key
        mode: 0600
      when: 'task_roles | length > 0'
      notify:
        - Configure OVN central northbound DB for SSL (certs)
        - Configure OVN central northbound DB for SSL (ports)
        - Configure OVN central southbound DB for SSL (certs)
        - Configure OVN central southbound DB for SSL (ports)
        - Configure OVN IC northbound DB for SSL (certs)
        - Configure OVN IC northbound DB for SSL (ports)
        - Configure OVN IC southbound DB for SSL (certs)
        - Configure OVN IC southbound DB for SSL (ports)

    - name: Configure OVN central database
      template:
        src: ../files/ovn/ovn-central.tpl
        dest: /etc/default/ovn-central
      notify:
        - Restart OVN central
        - Configure OVN AZ name
        - Enable OVN IC route sharing
      when: '"central" in task_roles'

    - name: Configure OVN host
      template:
        src: ../files/ovn/ovn-host.tpl
        dest: /etc/default/ovn-host
      notify:
        - Restart OVN host
      when: '"host" in task_roles'

    - name: Create OVN IC override directory
      file:
        path: /etc/systemd/system/ovn-ic.service.d
        mode: 0755
        state: directory
      when: '"ic" in task_roles'

    - name: Transfer OVN IC override
      copy:
        content: |
          [Service]
          EnvironmentFile=-/etc/default/ovn-ic
          ExecStart=
          ExecStart=/usr/share/ovn/scripts/ovn-ctl start_ic --no-monitor $OVN_CTL_OPTS
        dest: /etc/systemd/system/ovn-ic.service.d/ansible.conf
      notify: Restart OVN IC
      when: '"ic" in task_roles'

    - name: Configure OVN IC database
      template:
        src: ../files/ovn/ovn-ic.tpl
        dest: /etc/default/ovn-ic
      notify:
        - Restart OVN IC databases
        - Restart OVN IC
      when: '"ic" in task_roles or "ic-db" in task_roles'

    - name: Transfer OVN aliases
      template:
        src: ../files/ovn/alias.sh.tpl
        dest: /etc/ovn/alias.sh
      when: 'task_roles | length > 0'
  handlers:
    - name: Configure OVN central northbound DB for SSL (certs)
      shell:
        cmd: "ovn-nbctl set-ssl /etc/ovn/{{ task_name }}.server.key /etc/ovn/{{ task_name }}.server.crt /etc/ovn/{{ task_name }}.ca.crt"
      when: '"central" in task_roles'

    - name: Configure OVN central northbound DB for SSL (ports)
      shell:
        cmd: "ovn-nbctl set-connection pssl:6641:[::]"
      when: '"central" in task_roles'

    - name: Configure OVN central southbound DB for SSL (certs)
      shell:
        cmd: "ovn-sbctl set-ssl /etc/ovn/{{ task_name }}.server.key /etc/ovn/{{ task_name }}.server.crt /etc/ovn/{{ task_name }}.ca.crt"
      when: '"central" in task_roles'

    - name: Configure OVN central southbound DB for SSL (ports)
      shell:
        cmd: "ovn-sbctl set-connection pssl:6642:[::]"
      when: '"central" in task_roles'

    - name: Configure OVN IC northbound DB for SSL (certs)
      shell:
        cmd: "ovn-ic-nbctl set-ssl /etc/ovn/{{ task_name }}.server.key /etc/ovn/{{ task_name }}.server.crt /etc/ovn/{{ task_name }}.ca.crt"
      when: '"ic-db" in task_roles'

    - name: Configure OVN IC northbound DB for SSL (ports)
      shell:
        cmd: "ovn-ic-nbctl set-connection pssl:6645:[::]"
      when: '"ic-db" in task_roles'

    - name: Configure OVN IC southbound DB for SSL (certs)
      shell:
        cmd: "ovn-ic-sbctl set-ssl /etc/ovn/{{ task_name }}.server.key /etc/ovn/{{ task_name }}.server.crt /etc/ovn/{{ task_name }}.ca.crt"
      when: '"ic-db" in task_roles'

    - name: Configure OVN IC southbound DB for SSL (ports)
      shell:
        cmd: "ovn-ic-sbctl set-connection pssl:6646:[::]"
      when: '"ic-db" in task_roles'

    - name: Restart OVN central
      systemd:
        name: ovn-central.service
        state: restarted

    - name: Restart OVN host
      systemd:
        name: ovn-host.service
        state: restarted

    - name: Restart OVN IC
      systemd:
        daemon_reload: true
        name: ovn-ic.service
        state: restarted
      when: '"ic" in task_roles'

    - name: Restart OVN IC databases
      systemd:
        name: ovn-ic-db.service
        state: restarted
      when: '"ic-db" in task_roles'

    - name: Configure OVN AZ name
      shell:
        cmd: "ovn-nbctl --db={{ task_central_northbound }} -c /etc/ovn/{{ task_name }}.server.crt -p /etc/ovn/{{ task_name }}.server.key -C /etc/ovn/{{ task_name }}.ca.crt set NB_Global . name={{ task_az_name }}"
      when: '"central" in task_roles and task_az_name'

    - name: Enable OVN IC route sharing
      shell:
        cmd: "ovn-nbctl --db={{ task_central_northbound }} -c /etc/ovn/{{ task_name }}.server.crt -p /etc/ovn/{{ task_name }}.server.key -C /etc/ovn/{{ task_name }}.ca.crt set NB_Global . options:ic-route-adv=true options:ic-route-learn=true"
      when: '"central" in task_roles and task_az_name'
