#SPDX-License-Identifier: Apache-2.0
---
- name: Create cluster directory
  delegate_to: 127.0.0.1
  file:
    path: "../data/ovn/{{ task_name }}"
    mode: 0755
    state: directory
  throttle: 1
  when: '"central" in task_roles or "host" in task_roles'

- name: Create CA private key
  delegate_to: 127.0.0.1
  community.crypto.openssl_privatekey:
    path: "{{ task_pki_path }}/ca.key"
  register: ca_key
  throttle: 1
  when: '"central" in task_roles or "host" in task_roles'

- name: Create CA signing request
  delegate_to: 127.0.0.1
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ task_pki_path }}/ca.key"
    common_name: "OVN CA for {{ task_name }}"
    use_common_name_for_san: false
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr
  when: "ca_key.changed"
  throttle: 1

- name: Issue CA certificate
  delegate_to: 127.0.0.1
  community.crypto.x509_certificate:
    path: "{{ task_pki_path }}/ca.crt"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ task_pki_path }}/ca.key"
    provider: selfsigned
  when: "ca_csr.changed"
  throttle: 1

- name: Create server keys
  delegate_to: 127.0.0.1
  community.crypto.openssl_privatekey:
    path: "{{ task_pki_path }}/{{ inventory_hostname }}.key"
  register: cert_key
  when: 'task_roles | length > 0'

- name: Create server signing request
  delegate_to: 127.0.0.1
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ task_pki_path }}/{{ inventory_hostname }}.key"
    common_name: "OVN certificate for {{ inventory_hostname }}"
    use_common_name_for_san: false
  register: cert_csr
  when: "cert_key.changed"

- name: Issue server certificate
  delegate_to: 127.0.0.1
  community.crypto.x509_certificate:
    path: "{{ task_pki_path }}/{{ inventory_hostname }}.crt"
    csr_content: "{{ cert_csr.csr }}"
    ownca_path: "{{ task_pki_path }}/ca.crt"
    ownca_privatekey_path: "{{ task_pki_path }}/ca.key"
    ownca_not_after: "+3650d"
    ownca_not_before: "-1d"
    provider: ownca
  when: "cert_csr.changed"
  throttle: 1

- name: Create client keys
  delegate_to: 127.0.0.1
  community.crypto.openssl_privatekey:
    path: "{{ task_pki_path }}/{{ item }}.key"
  register: client_key
  when: 'task_roles | length > 0'
  loop: "{{ task_clients }}"
  throttle: 1

- name: Create client signing request
  delegate_to: 127.0.0.1
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ task_pki_path }}/{{ item.item }}.key"
    common_name: "OVN client certificate for {{ item.item }}"
    use_common_name_for_san: false
  register: client_csr
  loop: "{{ client_key.results }}"
  when: "client_key.changed"

- name: Issue client certificate
  delegate_to: 127.0.0.1
  community.crypto.x509_certificate:
    path: "{{ task_pki_path }}/{{ item.item.item }}.crt"
    csr_content: "{{ item.csr }}"
    ownca_path: "{{ task_pki_path }}/ca.crt"
    ownca_privatekey_path: "{{ task_pki_path }}/ca.key"
    ownca_not_after: "+3650d"
    ownca_not_before: "-1d"
    provider: ownca
  loop: "{{ client_csr.results }}"
  when: "client_csr.changed"
  throttle: 1
