# SPDX-License-Identifier: Apache-2.0
---
- name: Install debian repository
  ansible.builtin.import_tasks: repo_deb.yml
  when: 'ansible_distribution in ("Ubuntu", "Debian")'

- name: Install centos repository
  ansible.builtin.import_tasks: repo_dnf.yml
  when: 'ansible_distribution == "CentOS"'

- name: Force handler execution
  ansible.builtin.meta: flush_handlers

- name: Install packages
  ansible.builtin.import_tasks: packages.yml
