# SPDX-License-Identifier: Apache-2.0
---
- name: Bootstrap Ceph OSD
  ansible.builtin.command:
    cmd: ceph-volume lvm create --data /dev/disk/by-id/{{ item.data }}{% if "db" in item %} --block.db /dev/disk/by-id/{{ item.db }}{% endif %}
    creates: /var/lib/ceph/osd/.{{ item.data }}.created
  loop: '{{ ceph_disks }}'
  when: '"osd" in ceph_roles'
  changed_when: true

- name: Bootstrap Ceph OSD (stamp)
  ansible.builtin.command:
    cmd: touch /var/lib/ceph/osd/.{{ item.data }}.created
    creates: /var/lib/ceph/osd/.{{ item.data }}.created
  loop: '{{ ceph_disks }}'
  when: '"osd" in ceph_roles'
  changed_when: true
