- name: Run early playbook before incus installation
  import_playbook: books/local.early.yaml

- name: Install and configure Incus and its whole stack
  hosts: all
  order: shuffle
  gather_facts: true
  gather_subset:
    - "default_ipv4"
    - "default_ipv6"
    - "distribution_release"
  any_errors_fatal: true
  vars:
    config_root_dir: "{{ '.' | ansible.builtin.realpath }}"
  roles:
    - role: lxc.incus.system_settings
    - role: lxc.incus.netplan
      when: ansible_distribution in ("Ubuntu", "Debian")
    - role: lxc.incus.ntp
    - role: lxc.incus.nvme
    - role: lxc.incus.ceph
    - role: lxc.incus.linstor
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version in ("22.04", "24.04")
    - role: lxc.incus.lvmcluster
    - role: lxc.incus.ovn
      when: ansible_distribution in ("Ubuntu", "Debian")
    - role: lxc.incus.incus

- name: Run late playbook after incus installation
  import_playbook: books/local.late.yaml
