# SPDX-License-Identifier: Apache-2.0
---
- name: Check if distribution is supported
  ansible.builtin.meta: end_play
  when: 'ansible_distribution not in ("Ubuntu", "Debian", "CentOS")'

- name: Add the Debian repository registration
  ansible.builtin.import_tasks: "repo_deb.yml"

- name: Add the CentOS repository registration
  ansible.builtin.import_tasks: repo_dnf.yml

- name: Run the package and configuration for Incus
  ansible.builtin.import_tasks: installation.yml
